closeComment: >
  This issue has been closed automatically as it did not follow the issue template, please **open a new issue** that follows the bug report or feature request template.<br><br>

  If you would like to submit a support issue or get a faster reply, please consider [supporting me on Patreon](https://www.patreon.com/mattlewis92).<br><br>
  
  Thank you! ✌️

skipAuthors:
  - mattlewis92
