closeComment: >
  This issue has been closed automatically as it did not follow the issue template. Please open a new issue that follows the bug report or feature request template. Thank you! ✌️
  
reopenComment: >
  The issue has been re-opened as it has been edited to follow the issue template. Thanks for your co-operation 👍
