language: node_js

node_js:
  - '12'

script:
  - npx @angular/cli analytics off
  - npm test

notifications:
  email: false

cache:
  directories:
    - node_modules

after_success:
  - npm run codecov

sudo: required

addons:
  chrome: stable

dist: trusty
