language: node_js

node_js:
  - '12'

before_install: npx @angular/cli analytics off

script: npm test

notifications:
  email: false

cache:
  directories:
    - node_modules

after_success:
  - npm run codecov

sudo: required

addons:
  chrome: stable

dist: trusty
